---
title: "課?<a0>?練習模<e7><89><88>"
author: "Larry Hsieh"
date: "2020-10-20"
output: output_format
params:
  id: "410777098"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code
```{r}
library(lubridate)
```

```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
#ymd year/month/date
```

```{r}
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
#mdy month/ date / year
```

```{r}
tpeTime <- 
  ymd_hms(
    c("2020-03-18 13:52:40","2020-03-11 03:12:40"),
    tz="Asia/Taipei"
    )
#create a vector
#若時間字串來自UTC，那可以不設定tz參數
```

```{r}
tpeTimetest <- 
  ymd_hms(
    c("2020-03-18 13:52:40","2020-03-11 03:12:40"))
```

```{r}
tpeTimetest
```




```{r}
ymd_hms("2020-03-11T06:56:17Z")
```


#type/class
```{r}
typeof(tpeTime)
class(tpeTime)
#(class)ct:calender date t:time
```

```{r}
tpeTime
print(tpeTime)
cat(tpeTime) #only have digits
#the num stands for the seconds compared to 1970/01/01/00:00:00
```

```{r}
as.numeric(tpeTime)
```
```{r}
print(as.character(tpeTime))
cat(as.character(tpeTime)) #showing without[] (for reading) but won't show time zone
```

#Human tell computer the time
```{r}
tpeTime2 <- ymd_hms("2010-03-18 16:52:40",
                    tz="Asia/Taipei")
pgTime2 <- mdy_hms("Mar.01, 2020, 03:52:40",
                   tz="Europe/Lisbon")
```

#Let computer tells human the time
```{r}
tpeTime3 <- with_tz(tpeTime2,
        tzone="America/New_York")
tpeTime2
tpeTime3
typeof(tpeTime3)
class(tpeTime3)
```

"2020-03-18 13:52:40" Taipei

```{r}
tpeTime2
```
"2020-03-18 13:52:40" Taipei => NY
```{r}
tpeTime3
#EDT D stands for Day conserving time
```
```{r}
cat(tpeTime2)
print("\n")
cat(tpeTime3)
# the same distance
```

```{r}
pgTime3 <- 
  with_tz(pgTime2,
          tzone="America/New_York")
pgTime2
pgTime3
#EST S stands for ordinary time
```

```{r}
tpeTime3
pgTime3
```

```{r}
tpeTime3-pgTime3
tpeTime2-pgTime2
```
```{r}

```

```{r}
tpeTime
class(tpeTime)
as.character(tpeTime)
#as character the time zone will disappear
#often regards the time zone is UTC
```

#cannot assured whether the user is R language user so you need to as.character in UTC
```{r}
tpeTime_utc <- with_tz(tpeTime,
                       tzone="UTC")
tpeTime_utc
as.character(tpeTime_utc)
```

```{r}
tpeTime_iso8601 <- format_ISO8601(tpeTime, usetz=T)
tpeTime_iso8601
```

```{r}
tpeTime <- ymd_hms(tpeTime_iso8601)
```





