---
title: "課?<a0>?練習模<e7><89><88>"
author: "Larry Hsieh"
date: "2020-11-18"
output: output_format
params:
  id: "410777098"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
AA = c(Mary=176, John=188, Jenny= 165, Kate=170)
LL = list(
  Mary=list(176,"Taipei"),
  John=list(188,"New Taipei"),
  Jenny=list(165,"Taichung"),
  Kate=list(170,"Hualien")
)
```

```{r}
AA[[1]] #[[]]只拿元素

AA[1] #刪掉234,故名稱還會存在
```

```{r}
str(LL)
```

```{r}
LL[[1]]
LL[1]
```

```{r}
str(LL[[1]])
```

```{r}
str(LL[1])
```

```{r}
AA[[1]]
AA[["Mary"]]
```
```{r}
AA[1]
AA["Mary"]
```
```{r}
LL[[1]]
LL[["Mary"]]
LL$Mary
```

```{r}
LL[1]
LL["Mary"]
```
```{r}
AA[c(1,4)]
AA[c("Mary","Kate")]
AA[c(T, F, F, T)]
```

```{r}
LL[c(1,4)]
LL[c("Mary","Kate")]
LL[c(T, F, F, T)]
```

```{r}
a <- c(2, 5, 7)
length(a)
a[[4]]
```
```{r}
a[[4]] <- 8
print(a)
```
```{r}
library(lubridate)
```

```{r}
restaurant = "すき家 Sukiya (新北三峽店)"
date = lubridate::mdy("Nov 10, 2020")
order = list(
  list(
    item="番茄牛丼",
    quantity=1
  ) # 這裡少了一筆 "起司蕃茄牛丼"
)
total = 328
```

```{r}
oneOrder <- list(
  "restaurant"=restaurant,
  "date"=date,
  "order"=order,
  "total"=total
)
oneOrder
```
```{r}
View(oneOrder)
```

```{r}
oneOrder$order[[2]]
```

```{r}
oneOrder$order[[2]] <- list(
    item="起司蕃茄牛丼",
    quantity=1
  )
```

```{r}
template <- oneOrder$order[[1]]

template$item <- "起司蕃茄牛丼"
template$quantity <- 1

oneOrder$order[[2]] <- template
```
```{r}
oneOrder
```

```{r}
a <- c(2, 5, 7)
a[c(4,5)]
```
```{r}
a[c(4,5)] <- c(8, 12)
print(a)
```
```{r}
oneOrder$order[[3]]
```
```{r}
oneOrder$order[[4]]
```
```{r}
oneOrder$order[c(3,4)] <- list(
    list(
      item="牛丼飯",
      quantity=1
    ),
    list(
      item="豬排飯",
      quantity=1
    )
  )
```

```{r}
# 取出目前已有的子元素一個當模版
secondItem <- oneItem <- oneOrder$order[[1]]

oneItem$item <- "牛丼飯"
oneItem$quantity <- 1
secondItem$item <- "豬排飯"
secondItem$quantity <- 1

oneOrder$order[c(3,4)] <- list(
  oneItem, secondItem
)
```


```{r}
oneOrder$order
```


```{r}
#番茄牛丼改成2份
oneOrder$order[[1]]$quantity
```
```{r}
oneOrder$order[[1]]$quantity <- 2
oneOrder$order[[1]]$quantity
```
```{r}
allMyOrders0 <- allMyOrders <-  # allMyOrder0等一下還原用
  list(
    oneOrder
  )
```


```{r}
anotherOrder <- 
  list(
    restaurant="古橋飲食店",
    date=lubridate::mdy("Nov 9, 2020"),
    order=list(
      list(
        item="古早味排骨飯",
        quantity=1
      )
    ),
    total=89
  )
thirdOrder <-
  list(
    restaurant="Tijo Kitchen",
    date=lubridate::mdy("Nov 8, 2020"),
    order=list(
      list(
        item="韓式泡菜黑咖哩飯",
        quantity=1
      )
    )
  )
```

```{r}
allMyOrders[[2]]<- anotherOrder
allMyOrders[[3]]<- thirdOrder
allMyOrders
```

```{r}
#一次增加
allMyOrders[c(2,3)] <- list(anotherOrder, thirdOrder)
```

```{r}
length(allMyOrders)
str(allMyOrders)
```

```{r}
anotherOrder
length(anotherOrder)
```

```{r}
thirdOrder
length(thirdOrder)
```

```{r}
length(allMyOrders)
allMyOrders
```

```{r}
#original failed solution
allMyOrders[[3]]["total"]<-list(total=160)

allMyOrders
```



```{r}
#new solution1
newthirdOrder<-anotherOrder

newthirdOrder$restaurant<-thirdOrder$restaurant
newthirdOrder$date<-thirdOrder$date
newthirdOrder$order<-thirdOrder$order
newthirdOrder$total<-160

allMyOrders[[3]]<-newthirdOrder

allMyOrders
```


```{r}
#new solution2
thirdOrder<-  list(
    restaurant="Tijo Kitchen",
    date=lubridate::mdy("Nov 8, 2020"),
    order=list(
      list(
        item="韓式泡菜黑咖哩飯",
        quantity=1
      )
    ),
    total=160
  )

allMyOrders[[3]]<-thirdOrder

allMyOrders
```









