---
title: "課?<a0>?練習模<e7><89><88>"
author: "Larry Hsieh"
date: "2021-01-01"
output: output_format
params:
  id: "410777098"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

##5.2.1 if
```{r}
library(lubridate)
library(stringr)
library(purrr)
```

```{r}
bill<-250

hasVoucher<- TRUE

if(hasVoucher)
{
  bill<-bill-20
}
bill
```
```{r}
bill<-250

hasVoucher<- FALSE

if(hasVoucher)
{
  bill<-bill-20
}
bill
```


```{r}
set.seed(10739)

customers <- data.frame(
  bills = sample(200:500, 10),
  vouchers = sample(c(T,F), size=10, replace=T,
                     prob=c(0.4,0.6)
                     )
)

head(customers)
```
```{r}
bill <- customers$bills[[3]]
hasVoucher <- customers$vouchers[[3]]

totalBill <- 
{
  startingBill <- bill
  if(hasVoucher)
  {
    bill <- bill - 20
  }
  message("You initial bill is ", startingBill,".\n",
          "You final bill is ", bill)
  bill
}

print(totalBill)
```

```{r}
get_totalBill <- function(bill, hasVoucher)
{
  startingBill <- bill
  if(hasVoucher)
  {
    bill <- bill - 20
  }
  message("You initial bill is ", startingBill,".\n",
          "You final bill is ", bill, "\n")
  bill
}
```

```{r}
get_totalBill(
  customers$bills[[6]],
  customers$vouchers[[6]]
)
```

```{r}
library(maps)
```

```{r}
class(customers)
```

```{r}
map(
  seq_along(customers),
  ~{
    get_totalBill(
        customers$bills[[.x]],
        customers$vouchers[[.x]]
    )
  }
)
```

```{r}
purrr::map2(
customers$bills, customers$vouchers,
  ~{get_totalBill(.x, .y)}
)
```

```{r}
f <- function(x){
  if(x<0)
  {
    stop("x has to be non-negative.") 
    #stop and end
  }
  
  sqrt(x)
}
```

```{r}
f(2)
f(10)
f(-2)
f(2)
```

```{r}
comment_grade <- function(grade){
  if(grade < 60)
  {
    return("Don't give up. There is still hope.")
    #function才可以用return
  }
  
  return("Good job. Keep going")
}
```

```{r}
comment_grade(59)
comment_grade(60)
```

```{r}
df_grades <- data.frame(
  grade=sample(50:95, 20, replace = T)
)
df_grades
```

```{r}
comment_grade(df_grades$grade[[1]])
comment_grade(df_grades$grade[[11]])
```

```{r}
map(seq_along(df_grades$grade),
  ~{
    comment_grade(df_grades$grade[[.x]])
    }
)
```

```{r}
map(
  df_grades$grade,
  comment_grade
)
```

```{r}
unlist(map(
  df_grades$grade,
  comment_grade
))->df_grades$comment
```


```{r}
purrr::map_chr(
  df_grades$grade,
  comment_grade
) -> df_grades$comment
```

#5.2.2
```{r}
grades <- c(55, 72, 40) 
# fail in first

# any one failed? 
if(grades < 60) 
{message("\nYes, someone failed")
}
```

```{r}
grades <- c(72, 55, 40) # fail in second
# any one failed? 
if(grades < 60) message("\nYes, someone failed")
```
```{r}
#all() to flag if all failed.
#全都fail才true

#any() to flag if any failed.
#只要有一個fail就true
```

```{r}
grades <- c(72, 55, 82)
# any one failed? 
if(any(grades < 60)) message("\nYes, someone failed")
```

```{r}
Sys.setenv("_R_CHECK_LENGTH_1_CONDITION_" = "true")
```

```{r}
grades <- c(55, 72, 82)
# any one failed? 
if(grades < 60) message("\nYes, someone failed") # error now
```
#5.2.3
```{r}
#To judge if all conditions hold, a proper flag should be from && than &.

#To judge if any condition hold, a proper flag should be from || than |.
```

```{r}
#(isMale) && (olderThan36): Conditions are check sequentially. When one is FALSE, there is no need to check subsequent conditions (more efficient); a FALSE is concluded.
```

```{r}
grade1 <- list(
  economics=55,
  calculus=77
)
grade2 <- c(
  economics=55,
  calculus=77
)
```

```{r}
(is.list(grade1) &  grade1$economics > 60)
(is.list(grade2) &&  grade2$economics > 60)
(is.list(grade2) &  grade2$economics > 60)
```

```{r}
myAge <- 75

if(myAge >=65 | stop("Error")){
  "Qualified"
} else {
  warning("Not qualified")
}
```

```{r}
myAge <- 75
if(myAge >=65 ||  stop("Error")){
  "Qualified"
} else {
  warning("Not qualified")
}
```
#5.2.4 if else
```{r}
# 前提條件
x <- 4L
# 任務
fx <- {
  
  # ending scenario 1:
  if(x %% 2 ==0)
  {
    x/2
  } else #else must follow } immediately in the same line
  # ending scenario 2:
  {
    -(x+1)/2
  }
}

fx
```

```{r}
fx <- function(x)
{
  # ending scenario 1:
  if(x %% 2 ==0)
  {
    return(x/2)
  } else
  # ending scenario 2:
  {
    return(-(x+1)/2)
  }
}
```

```{r}
fx(4L)
fx(7L)
```

```{r}
# 前提
grade <- 88
# 任務
comment <- 
{
  if(grade>=90)
  {
    "優"
  } else if(grade >=80 && grade <=89)
  {
    "良"
  } else if(grade>=70 && grade <=79)
  {
    "尚可"
  } else
  {
    "待加強"
  }
}

comment
```

```{r}
comment_grade <- function(grade){
  if(grade>=90)
  {
    "優"
  } 
  else if(grade >=80 && grade <=89)
  {
    "良"
  } 
  else if(grade>=70 && grade <=79)
  {
    "尚可"
  } 
  else
  {
    "待加強"
  }
}
```


```{r}
comment_grade(95)
```

```{r}
comment_grade <- function(grade){
  if(grade>=85)
  {
    "優"
  } else
  if(grade >=80 && grade <=89)
  {
    "良"
  } else
  if(grade>=70 && grade <=79)
  {
    "尚可"
  } else
  {
    "待加強"
  }
}

#If there are multiple TRUE flags from different if-condition expressions, ONLY the programming block follows the FIRST TRUE flag will be executed
comment_grade(86)
```

#5.2.6 switch
```{r}
sortedEmails <- list(
  office=character(),
  student=character(),
  private=character()
)
```

```{r}
set.seed(2839)
emailFrom <- sample(
  c("econ@gm.ntpu.edu.tw","classStudents@gm.ntpu.edu.tw","xxx@gmail.com","econStaff@gm.ntpu.edu.tw","yyyy@gmail.com"), 50,
  replace=T
)
head(emailFrom, 10)
```

```{r}
.x<- 3
commingEmail <- emailFrom[[.x]]
```

```{r}
# Office
{
  message("You have a message from office.")
  nOffice <- length(sortedEmails$office)
  sortedEmails$office[[nOffice+1]] <- commingEmail
  sortedEmails
}
# Student
{
  message("There is an email from student in your class.")
  nStudent <- length(sortedEmails$student)
  sortedEmails$student[[nStudent+1]] <- commingEmail
  sortedEmails
}
# Private
{
  message("A private message has come in.")
  nPrivate <- length(sortedEmails$private)
  sortedEmails$private[[nPrivate+1]] <- commingEmail
  sortedEmails
}
```

```{r}
library(stringr)
```

```{r}
condition_sgn <- 
  ifelse(
    str_detect(commingEmail,"econ"), "office", commingEmail)
```

```{r}
condition_sgn
```
```{r}
commingEmail
str_detect(commingEmail,"econ")
```

```{r}
sortedEmails <- list(
  office=character(),
  student=character(),
  private=character()
)
```

```{r}
emailFrom
```


```{r}
map(seq_along(emailFrom),
  ~{commingEmail <- emailFrom[[.x]]}
) 
```


```{r}

switch(
  condition_sgn,
  "office"={
    message("You have a message from office.")
    nOffice <- length(sortedEmails$office)
    sortedEmails$office[[nOffice+1]] <- commingEmail
    sortedEmails
  },
  "classStudents@gm.ntpu.edu.tw"={
    message("There is an email from student in your class.")
    nStudent <- length(sortedEmails$student)
    sortedEmails$student[[nStudent+1]] <- commingEmail
    sortedEmails
  },
  {
    message("A private message has come in.")
    nPrivate <- length(sortedEmails$private)
    sortedEmails$private[[nPrivate+1]] <- commingEmail
    sortedEmails
  }
)
```



